services:
  - type: static
    name: risklayer-frontend
    env: static
    # Root directory is now current folder
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      # This handles the 404 issue on refresh
      - source: /*
        destination: /index.html
        type: rewrite
